# Tests PRs on multiple operating systems and Python/Java versions
name: Test Build

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main
    paths-ignore:
      - 'LICENSE*'
      - '.gitignore'
      - '**.md'
      - '**.adoc'
      - '*.txt'
      - '.ci/**'

defaults:
  run:
    shell: bash

jobs:
  test-build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 17 ]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'
      # Need to install both Python 3.9, Python 3.10 and Python 3.11 for tox (has to be in the same run)
      # Feature Request for setup action: https://github.com/actions/setup-python/issues/98
      - name: Python 3.9 Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            **/setup.py
      - name: Python 3.10 Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            **/setup.py
      - name: Python 3.11 Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            **/setup.py
      - name: Install tox
        run:
          python -m pip install --upgrade pip
          pip install tox pytest
      - name: Build with Maven to install parent poms for python build
        run: mvn -B --fail-at-end clean install
      - name: Run tox on timefold solver python test suite
        run: python -m tox
      - name: Run tox on jpyinterpreter test suite
        working-directory: ./jpyinterpreter
        run: python -m tox
